name: CI/CD

on:
  push:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Check linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs:
      lint
    services:
      localstack:
        image: localstack/localstack
        ports:
          - "4566:4566"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env:
          DISABLE_CORS_CHECKS: 1
          DYNAMODB_SHARE_DB: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Initialize LocalStack resources
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ENDPOINT_URL: http://localhost:4566/
          AWS_ACCESS_KEY_ID: xxx
          AWS_SECRET_ACCESS_KEY: yyy

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Run Tests
        run: make test

      - name: Run E2E tests
        run: cd ./app && make e2etest

#  deploy:
#    runs-on: ubuntu-latest
#    needs:
#      test
#    permissions:
#      id-token: write
#      contents: read
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version-file: '.nvmrc'
#
#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
#          role-session-name: Github-${{ github.event.repository.name }}-${{ github.run_id }}
#          aws-region: "ap-northeast-1"
#
#      - name: Update Code
#        run: make deploy AWSCLI=aws
